services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=authorization-server-db'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '15432:5432'
  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_HOST_PASSWORD}"]
    ports:
      - '16379:6379'
    env_file:
      - .env