spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:postgresql://postgres:5432/authorization-server-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  profiles:
    include:
      - oauth2
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_HOST_PASSWORD}
server:
  port: 9000
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
