spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:postgresql://localhost:15432/authorization-server-db
    username: phatdo
    password: bimatnha
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  profiles:
    include:
      - oauth2
server:
  port: 9000
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
